### ISSUE TITLE
ETA for full dataset release?

### ISSUE THREAD

**Issue by purvaten** [snuvclab/ParaHome#1]
Hi, congratulations on the cool work! It appears that only the demo data has been released for 5 sequences. When will the full dataset be made available? I plan to use it for my own research.

Thank you.

**Comment by hongzhengdong** [comment]
We are looking forward to it, too

**Comment by canoneod** [comment]
Hi, and thank you for your interest in our dataset! We are currently processing all of our data, and it might take some time to finish all of them. We aim to release it before July, but please be aware that this timeline could change.

**Comment by EmptyBlueBox** [comment]
Hi! Thank you for your wonderful work! 

Wondering when the full dataset can be available? It's June 30 now and I'm thinking to use it for my research! 

Thank you very much!

**Comment by jlogkim** [comment]
@EmptyBlueBox Hello. Sorry for the delayed response. The ParaHome dataset has been released.
