### ISSUE TITLE
How to use --fromto in render.py ？

### ISSUE THREAD

**Issue by Ingrid789** [snuvclab/ParaHome#5]
ParaHome is an excellent project! I am currently trying to utilize the data in the bone_vectors.pkl and body_joint_orientations.pkl files. However, I am experiencing some difficulties in using these files with render.py, as the data in bone_vectors.pkl appears to be different from its expected Python usage.

Could you please provide an example to use these files? Additionally, could you release a corrected version of bone_vectors.pkl?

Thank you!

**Comment by canoneod** [comment]
Thank you for your kind words! We've just found that part of our data was written in wrong format and the fixed version of 'seq' folder has been updated. Please let us know if it still doesn't work!
