### ISSUE TITLE
Articulated object axis/pivot points

### ISSUE THREAD

**Issue by safdarzareef** [snuvclab/ParaHome#6]
Hi, thank you so much for the useful dataset! 

Would it be possible to get the articulation axis and the pivot points for the scanned objects?

**Comment by canoneod** [comment]
Sorry for the late reply. I've just uploaded data in joint_info.pkl which you can find in the provided link at readme.md. Let us know if  there is any other issue!

**Comment by safdarzareef** [comment]
Thanks for sharing! I really appreciate the help :smile:
