### ISSUE TITLE
Questions about missing text_annotation.json & object_transformations.pkl & head_tips.pkl & joint_positions.pkl files in folder s6 ~ s207?

### ISSUE THREAD

**Issue by Ingrid789** [snuvclab/ParaHome#7]

**Comment by canoneod** [comment]
Oops, we've found there was issue in processing the data. Just fixed and re-uploaded seq.zip file in the link at readme.md. Let us know if there is any other issue!

**Comment by Ingrid789** [comment]
Thanks a lot!
